### ISSUE TITLE
Icons are vertical, not horizontal

### ISSUE THREAD

**Issue by NickHodges** [silent1mezzo/astro-social-share#16]
The icons appear to be the right size, but now they are vertical.  I presume the default should be horizontal

![image](https://github.com/silent1mezzo/astro-social-share/assets/1060358/1b4cd4f6-bb5f-4503-9d90-2731055f6db6)

Thanks for working on this!

**Comment by silent1mezzo** [comment]
@NickHodges are you using an open source theme I could test it on? I've tested it on a number now, including an entirely blank page and they all show up horizontal for me.

e.g. https://mckerlie.com/posts/improving-the-sharing-experience-in-astro/

and on a blank page

<img width="336" alt="Screenshot 2024-07-01 at 8 21 12 AM" src="https://github.com/silent1mezzo/astro-social-share/assets/155016/5f58f5fb-cd9a-4f0e-8941-1f62a3529399">

**Comment by NickHodges** [comment]
My site is here:

https://github.com/NickHodges/Nick-Blog

If that helps.

I'm testing it out in the `social` branch.

**Comment by silent1mezzo** [comment]
Perfect, found the theme. I just pushed [v2.0.1](https://www.npmjs.com/package/astro-social-share) to fix it

**Comment by NickHodges** [comment]
Hey, that works better!  I'l have to see with there is all that padding on the top of the control, but it looks much better! Thank you!

![image](https://github.com/silent1mezzo/astro-social-share/assets/1060358/f2b10140-e099-4747-83bd-c5c39c9cfb0c)
