### ISSUE TITLE
`url` can't be overwritten which leads to failure in static site generation

### ISSUE THREAD

**Issue by madrobby** [silent1mezzo/astro-social-share#18]
Because `url` is based on the Astro request, the buttons fail to correctly generate when used with static sites generated by Astro (they all point to `localhost:4321`).

**Comment by madrobby** [comment]
Take it back, you can actually set it!

**Comment by silent1mezzo** [comment]
@madrobby Leaving this for others who see this.

1. URL defaults to `Astro.requests.url` which I believe uses the base url you set in your astro config. You can see this working on my [blog](https://mckerlie.com/posts/improving-the-sharing-experience-in-astro/) and the [source code that controls it](https://github.com/silent1mezzo/mckerlie.com/blob/main/src/layouts/PostDetails.astro#L62).
2. `url` can be overridden if you want, you can include it with `SocialShare` component or any of the individual buttons.

e.g.
```
<SocialShare
    url="https://whateverurlyouwant.com"
    description="Description of the page/post"
    via="YourTwitterAccount"
    title="Page Title"
/>
```
