### ISSUE TITLE
Add rel="noopener noreferrer" to prevent tab nabbing

### ISSUE THREAD

**Issue by gilesbutler** [silent1mezzo/astro-social-share#7]
Hi there,

Thanks for the handy extension. Can you add `rel="noopener noreferrer"` to all the links? Or make it optional?

>Add the rel="noopener noreferrer" attribute to external links that open in a new tab or window. This prevents the newly opened tab from having access to the referring tab, which can help mitigate [tabnabbing](https://en.wikipedia.org/wiki/Tabnabbing).

We can't use the extension till it supports this as it fails our security rules unfortunately. 

Thanks

**Comment by silent1mezzo** [comment]
@gilesbutler thanks for the report. I'll add it and cut a release Sunday or Monday.

**Comment by gilesbutler** [comment]
Awesome, thanks @silent1mezzo 👍

**Comment by silent1mezzo** [comment]
@gilesbutler just published [v1.1.0 ](https://www.npmjs.com/package/astro-social-share/v/1.1.0) that contains this on all of the links.

**Comment by gilesbutler** [comment]
Amazing, thank you @silent1mezzo! Awesome stuff, really appreciate the fast turnaround 🙏
